package de.bo.aid.boese.homematic.model;
// default package
// Generated 31.08.2015 00:11:54 by Hibernate Tools 4.3.1

/**
 * Component generated by hbm2java
 */
public class Component implements java.io.Serializable {



	@Override
	public String toString() {
		return "Component [compid=" + compid + ", idverteiler=" + idverteiler + ", name=" + name + ", address="
				+ address + ", hm_id=" + hm_id + ", unit=" + unit + ", aktor=" + aktor + "]";
	}

	private int compid;
	private Device device;
	private Integer idverteiler;
	private String name;
	private String address;
	private String hm_id;
	private String unit;
	private boolean aktor;
	

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}


	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public boolean isAktor() {
		return aktor;
	}

	public void setAktor(boolean aktor) {
		this.aktor = aktor;
	}

	public Component() {
	}

	public Component(int compid, Device device) {
		this.compid = compid;
		this.device = device;
	}

	public Component(int compid, Device device, Integer idverteiler, String name) {
		this.compid = compid;
		this.device = device;
		this.idverteiler = idverteiler;
		this.name = name;
	}

	public int getCompid() {
		return this.compid;
	}

	public void setCompid(int compid) {
		this.compid = compid;
	}

	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	public Integer getIdverteiler() {
		return this.idverteiler;
	}

	public void setIdverteiler(Integer idverteiler) {
		this.idverteiler = idverteiler;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getHm_id() {
		return hm_id;
	}

	public void setHm_id(String hm_id) {
		this.hm_id = hm_id;
	}
	

}
