package de.bo.aid.boese.homematic.model;
// default package
// Generated 31.08.2015 00:11:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Connector generated by hbm2java
 */
public class Connector implements java.io.Serializable {

	private int conid;
	private Integer idverteiler;
	private String secret;
	private String name;
	private Set devices = new HashSet(0);

	public Connector() {
	}

	public Connector(int conid) {
		this.conid = conid;
	}

	public Connector(int conid, Integer idverteiler, String secret, String name, Set devices) {
		this.conid = conid;
		this.idverteiler = idverteiler;
		this.secret = secret;
		this.name = name;
		this.devices = devices;
	}

	public int getConid() {
		return this.conid;
	}

	public void setConid(int conid) {
		this.conid = conid;
	}

	public Integer getIdverteiler() {
		return this.idverteiler;
	}

	public void setIdverteiler(Integer idverteiler) {
		this.idverteiler = idverteiler;
	}

	public String getSecret() {
		return this.secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDevices() {
		return this.devices;
	}

	public void setDevices(Set devices) {
		this.devices = devices;
	}

}
