package de.bo.aid.boese.homematic.model;
// default package
// Generated 31.08.2015 00:11:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	private int devid;
	private Connector connector;
	private Integer idverteiler;
	private String adress;
	private String type;
	private int version;
	private Set<Component> components = new HashSet<Component>(0);

	public Device() {
	}

	public Device(int devid, Connector connector) {
		this.devid = devid;
		this.connector = connector;
	}

	public Device(int devid, Connector connector, Integer idverteiler, Set<Component> components) {
		this.devid = devid;
		this.connector = connector;
		this.idverteiler = idverteiler;
		this.components = components;
	}

	public int getDevid() {
		return this.devid;
	}

	public void setDevid(int devid) {
		this.devid = devid;
	}

	public Connector getConnector() {
		return this.connector;
	}

	public void setConnector(Connector connector) {
		this.connector = connector;
	}

	public Integer getIdverteiler() {
		return this.idverteiler;
	}

	public void setIdverteiler(Integer idverteiler) {
		this.idverteiler = idverteiler;
	}


	public String getAdress() {
		return adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public Set<Component> getComponents() {
		return this.components;
	}

	public void setComponents(Set<Component> components) {
		this.components = components;
	}
	
	public String getName(){
		return "HM_" + type + "_" + adress;
	}

}
