package de.bo.aid.boese.homematic.model;
// default package
// Generated 31.08.2015 00:11:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	private int devid;
	private Connector connector;
	private Integer idverteiler;
	private String name;
	private Set<Component> components = new HashSet<Component>(0);

	public Device() {
	}

	public Device(int devid, Connector connector) {
		this.devid = devid;
		this.connector = connector;
	}

	public Device(int devid, Connector connector, Integer idverteiler, String name, Set<Component> components) {
		this.devid = devid;
		this.connector = connector;
		this.idverteiler = idverteiler;
		this.name = name;
		this.components = components;
	}

	public int getDevid() {
		return this.devid;
	}

	public void setDevid(int devid) {
		this.devid = devid;
	}

	public Connector getConnector() {
		return this.connector;
	}

	public void setConnector(Connector connector) {
		this.connector = connector;
	}

	public Integer getIdverteiler() {
		return this.idverteiler;
	}

	public void setIdverteiler(Integer idverteiler) {
		this.idverteiler = idverteiler;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Component> getComponents() {
		return this.components;
	}

	public void setComponents(Set<Component> components) {
		this.components = components;
	}

}
